"""Shared seller-side primitives for the modular discounted model."""

from __future__ import annotations

from dataclasses import asdict, dataclass
import math


@dataclass(frozen=True)
class SellerPrimitives:
    """Parameters that are common to every belief and demand rule.

    ``threshold`` is the continuation-gap cutoff used by the product choice:
    product 2 is optimal when the (discounted) value difference generated by a
    success rather than a failure is sufficiently large relative to
    ``(c2-c1)/(p2-p1)``.
    """

    p0: float = 0.50
    p1: float = 0.35
    p2: float = 0.80
    c1: float = 0.05
    c2: float = 0.65
    revenue: float = 1.00
    gamma: float = 0.98

    def __post_init__(self) -> None:
        values = asdict(self)
        if not all(math.isfinite(value) for value in values.values()):
            raise ValueError("all seller primitives must be finite")
        if not 0.0 <= self.p0 <= 1.0:
            raise ValueError("p0 must lie in [0, 1]")
        if not 0.0 <= self.p1 < self.p2 <= 1.0:
            raise ValueError("success probabilities must satisfy 0 <= p1 < p2 <= 1")
        if not self.c1 < self.c2:
            raise ValueError("costs must satisfy c1 < c2")
        if not 0.0 <= self.gamma < 1.0:
            raise ValueError("gamma must lie in [0, 1)")

    @property
    def threshold(self) -> float:
        """Cost-per-success cutoff ``(c2-c1)/(p2-p1)``."""

        return (self.c2 - self.c1) / (self.p2 - self.p1)

    @property
    def net_rewards(self) -> tuple[float, float]:
        """One-period profits of products 1 and 2 when A is selected."""

        return self.revenue - self.c1, self.revenue - self.c2

    def as_dict(self) -> dict[str, float]:
        """Return a fresh, serialization-friendly parameter dictionary."""

        return {key: float(value) for key, value in asdict(self).items()}
